vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        participant_images:
            uri_prefix: /images/profils
            upload_destination: '%kernel.project_dir%/public/images/profils'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        sortie_images:
            uri_prefix: /images/sorties
            upload_destination: '%kernel.project_dir%/public/images/sorties'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
